service: proof-culqi-ts-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:962904355404:table/CreditCard
plugins:
  - serverless-offline

functions:
  createToken:
    handler: ./dist/api/token.createToken
    events:
      - http:
          method: POST
          path: /token
resources:
  Resources:
    CrediCard:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CreditCard
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TimeToLiveSpecification:
            AttributeName: timeToLive
            Enabled: true
